import Head from 'next/head';
import Cronometro from '../src/components/cronometro';
import Form from '../src/components/form';
import List from '../src/components/list';
import { useState } from 'react';
import {tarefaProps} from '../src/interfaces';


export default function Home(){

  const [tarefas, setTarefas] = useState<tarefaProps[] | []>([]);
  const [selecionado, setSelecionado] = useState<tarefaProps >();

  function selecionaTarefa(tarefaSelecionada:tarefaProps){
    setSelecionado(tarefaSelecionada);
    setTarefas(tarefasAnteriores => tarefasAnteriores.map(tarefa=>({
      ...tarefa,
      selecionado: tarefa.id === tarefaSelecionada.id ? true : false
    })));
  }

  function finalizandoTarefa(){
    if(selecionado){
      setSelecionado(undefined);
      setTarefas(tarefasAnteriores=>tarefasAnteriores.map(tarefa=>{
        if(tarefa.id === selecionado.id){
          return{
            ...tarefa,
            selecionado:false,
            completado:true
          };
        }
        return tarefa;
      }));
    }
  }


  return (
    <div className='AppStyle'>
      <Head>
        <title>React Alura - johnatan</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        
      </Head>

      <Form setTarefas={setTarefas}/>

      <List 
        tarefas={tarefas}
        selecionaTarefa={selecionaTarefa}
        />

      <Cronometro 
        selecionado={selecionado} 
        finalizandoTarefa={finalizandoTarefa}
      /> 

    </div>
  );
}


